---
dataset:
  desc: name of the dataset
  value: a
  # value: b
  # value: c
epochs:
  desc: Number of epochs to train over
  value: 1000
device:
  desc: torch device to train on
  value: cuda:1
batch_size:
  desc: Size of each mini-batch
  value: 32
lr:
  desc: Learning rate
  value: 0.001
num_hidden_layers:
  desc: Number of hidden layers
  value: 2
hidden_dim:
  desc: Dimension of hidden layers
  value: 128
cost_0_classified_as_1:
  desc: cost of classifying true sample 0 (green) as label 1 (red)
  value: 1
cost_1_classified_as_0:
  desc: cost of classifying true sample 1 (red) as label 0 (green)
  value: 1
pert_norm:
  desc: which p-norm to use for the input perturbation (plots only supported for 2 and inf)
  # value: .inf
  value: 2
pert_eps:
  desc: epsilon for perturbation norm in verified accuracy
  value: 0.025
cache_model_name:
  desc: name of cached model (null to disable caching)
  value: artifacts/model_a_cost_1/model.torch
val_split:
  desc: fraction of the training data used as validation set
  value: 0
patience:
  desc: number of epochs used for early stopping (0 to disable early stopping)
  value: 200
weight_decay:
  desc: L2 penalty to impose on the weights for regularisation
  value: 0 # 0.01
dropout:
  desc: probability of a neuron input being zeroed during training for regularisation
  value: 0 # 0.25
dataset_type_train:
  desc: whether to use train or validation data input files
  value: False
